//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTCourse_ASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Course = new HashSet<Course>();
        }
        [DisplayName("User_ID")]
        public int User_ID { get; set; }
        [DisplayName("User_Name")]
        [Required(ErrorMessage = "{0} can't null, please enter")]
        public string User_Name { get; set; }
        [DisplayName("User_Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", ErrorMessage = "Email isn't valid.")]
        public string User_Email { get; set; }
        [DisplayName("User_Phone")]
        [RegularExpression(@"([0-9]){9}", ErrorMessage = "Phone Number must be 10 Digits Long and 0... .")]
        public Nullable<int> User_Phone { get; set; }
        [DisplayName("User_Address")]
        public string User_Address { get; set; }
        [DisplayName("User_Permission")]
        [Required(ErrorMessage = "{0} can't null, please enter")]
        public string User_Permission { get; set; }
        [DisplayName("User_Username")]
        [StringLength(20, ErrorMessage = "Username can't more than 20 Characters Long")]
        [Required(ErrorMessage = "{0} can't null, please enter")]
        public string User_Username { get; set; }
        [DisplayName("User_Password")]
        [Required(ErrorMessage = "{0} can't null, please enter")]
        public string User_Password { get; set; }

        public virtual User_Permission User_Permission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course { get; set; }
    }
}
